### PR TITLE
Docs cleanup - old todo pages, links etc.

### PR DESCRIPTION
**Pull request by keelanfh**
Several docs updates - mostly I just thought it wasn't that helpful to have blank pages listed as "todo" for a long time.

Also updating things like branch names, and removing references to IE11 support which no longer exists.

### CODE REVIEW

**Comment by keelanfh** [comment]
@finnlewis @msayoung would either of you have a chance to review/merge this one?

**Comment by msayoung** [comment]
@keelanfh - so sorry I didnt see this MR before. 
Looks great.

**Review by msayoung — APPROVED** [review]

**Comment by msayoung** [comment]
Need to work out why the checks are failing though.

**Comment by msayoung** [comment]
@stephen-cox 

I wonder if you could advise when you have a moment ?

**Comment by keelanfh** [comment]
@finnlewis @msayoung I've fixed the issue that was causing this to fail tests - could one of you merge this please?

**Pull request merged**
