### PR TITLE
Add basic documentation for the news feature

### PR DESCRIPTION
**Pull request by msayoung**
Some basic documentation for the News Feature. 
Any suggestions for improvements?

### CODE REVIEW

**Comment by willguv** [comment]
@msayoung I think this is a big step forward - thank you

I'm keen to think about the users of this page versus more technical pages like https://localgovdrupal.org/config/content-types.html#service-sub-landing-page. Let's talk about it at Review

**Comment by danchamp** [comment]
@msayoung This is great, thanks.

Only one suggested addition - in the News article config section, we could add a section for `Structured data` to reference the https://schema.org/NewsArticle implementation. I'm happy to pick this up if it's a good idea.

For Examples in the wild, London Councils are using an earlier version of the module that is functionally very similar (pagination being the major difference) here: https://beta.londoncouncils.gov.uk/

This could be included now, or we wait until it's updated to use the latest version.

**Comment by msayoung** [comment]
Hey @danchamp and @willguv 

There's more to review on this: 
https://deploy-preview-46--trusting-noyce-aebebc.netlify.app/features/news/

**Comment by willguv** [comment]
Hi @msayoung just read this through - there's only thing I would change 

On https://deploy-preview-46--trusting-noyce-aebebc.netlify.app/features/news, Croydon news uses Wordpress so we need to remove this link

If I knew how to do this without messing up your PR, then I would make this change myself :)

**Comment by willguv** [comment]
@msayoung I tried removing the Croydon link - please let me know if this has worked or not

**Comment by msayoung** [comment]
It worked @willguv :)

**Comment by willguv** [comment]
That’s great. Did it suggest changes to you, which you OK-ed?

Haven’t reviewed a PR in this way before, but starting to get the hang of it

**Pull request merged**
