### PR TITLE
Update README.md with named maintainers

### PR DESCRIPTION
**Pull request by finnlewis**
@msayoung added you and me for now... anyone else good to add?

### CODE REVIEW

**Review by msayoung — APPROVED** [review]

**Review by msayoung — CHANGES_REQUESTED** [review]
Actually, lets add @MichaelDCR if he's willing :)

**Comment by finnlewis** [comment]
@MichaelDCR - that OK with you?

**Comment by finnlewis** [comment]
Let's go with this for now, we can change easily at any point.

**Review by msayoung — APPROVED** [review]

**Comment by MichaelDCR** [comment]
Hi @msayoung @finnlewis 
I'm going to stop working on LGD from end of this month, so best take my name off it.

**Comment by msayoung** [comment]
:) we'll remove you in February

**Pull request merged**
