### PR TITLE
Add an overview for Developers

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by msayoung** [comment]
Hey @MichaelDCR @finnlewis - have a look at this, any suggestions for improvements? 

https://deploy-preview-92--trusting-noyce-aebebc.netlify.app/devs/

**Comment by MichaelDCR** [comment]
Looks good to me. 

I suppose we could leave the Roadmap out as it will be covered in Features on the main site, and I'm loathe to point people to the Trello board - it will get replaced but we're not sure what with.

**Comment by msayoung** [comment]
I've removed the Roadmap out, but added some introductory content. 
Whatdoyathink @finnlewis  ?
https://deploy-preview-92--trusting-noyce-aebebc.netlify.app/devs/

**Review by finnlewis — APPROVED** [review]
Made a few tweaks, looks good for now, thanks @msayoung !

**Pull request merged**
