### PR TITLE
Feature/add contribution guidelines

### PR DESCRIPTION
**Pull request by paulpopus**
Trying to add contribution guidelines and community information.

I don't quite know everything yet but happy for others to add to this or suggest specifics I shouldn't omit.

FAO @finnlewis @cjstevens78 @andybroomfield @stephen-cox @Adnan-cds

### CODE REVIEW

**Comment by paulpopus** [comment]
It has a nice little deploy preview https://deploy-preview-2--trusting-noyce-aebebc.netlify.app/contributing/

**Comment by finnlewis** [comment]
Great start @paulpopus - thanks - I'm keen to help the docs evolve as quickly as possible and think this will start to act as a first point of call for interested parties. 

I guess this is the start of a 'shop window' @willguv - but I do think that docs about how it works might evolve to be different from a what it does eventually having a promotional site separate from the documentation. 

But for now..  this is looking much better and more accessible than just README files in the GitHub repos.

**Review by finnlewis — APPROVED** [review]
Let's merge this on in @paulpopus , it is clearly improving the documentation, so we'll see in time how others feel about the look and feel of it, but at least it is a single place for us to focus our efforts.

**Pull request merged**
