### PR TITLE
Added GA4 code snippet

### LINKED ISSUE #148: Analytics on Docs pages
Can we add Google Analytics to the docs?

I found supposed method for Vuepress:
https://v2.vuepress.vuejs.org/reference/plugin/google-analytics.html
https://github.com/vuejs/vuepress/issues/2713
That doesn't provide any cookie consent, but I think we can be relaxed around that frankly. 

The GA4 measurement ID is:  G-ETT82J89DV

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #148

### CODE REVIEW

**Comment by MichaelDCR** [comment]
Hi @stephen-cox 
it looks good
debug of analytics tracking fails, but that may be for various reasons - if you deploy it then I can test properly

**Comment by stephen-cox** [comment]
@MichaelDCR This has been merged and deployed to the live site

**Comment by MichaelDCR** [comment]
Hi @stephen-cox it's not working. 

In debug the the Google Tag is found for the correct property, but no hits are being sent to analytics. 

Inspector shows the tag in Sources too. 

Not seen this before. Could be a Vuepress thing. Not sure how to debug further.

**Comment by stephen-cox** [comment]
The script is loading, but it's not setting cookies. Will need to investigate.

**Comment by stephen-cox** [comment]
I found a typo in the code I was adding to the page. GA cookies are now being set.

@MichaelDCR Is this now working for you?

**Comment by MichaelDCR** [comment]
Thanks @stephen-cox 

I can see data now (although it seems to have disappeared for the main site, which makes no sense and is probably some weird GA4 time delay bug) so reckon all is good

**Pull request merged**
