### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by msayoung** [comment]
Hi @MichaelDCR 
I fixed the broken links. 

I 'm not sure about "Back to main site" as there's no guarantee that's where people came from. 
I'm also not convinced about that being the main link, but I don't know what should be so we can leave it for now. 

I would also like to see a couple of sentences about what LocalGov Drupal is before diving in to the Quick links. 
I've done an alternative for you to see https://deploy-preview-98--trusting-noyce-aebebc.netlify.app/

**Comment by MichaelDCR** [comment]
thanks @msayoung 

Your version is ok to go live with, but are you happy for me to make another edit?

I disagree about the intro text and not having a 'main site' link. The only two routes to the Docs site should via the main site, or from a specific link that has context e.g. in an email or a starter pack document. So the intro text is not needed. 

We should probably have a 'main site' link in the top navigation anyway, which would reduce the need for a big one on the index page. We do need to remove the 'Blog' link from that nav.

**Comment by MichaelDCR** [comment]
by edit I mean to cut some of the intro text, and lose the main button 

the 'find out more' link doesn't have context where it is - no indication where it goes

**Comment by MichaelDCR** [comment]
cool, let's talk it through when there's less time pressure

I'll do a quick edit of your version

**Pull request closed without merging**
