### PR TITLE
Blogging

### PR DESCRIPTION
**Pull request by iam-jam**
* A new component that scans the content of the blog directory and prints out teasers for any files that aren't the index
* The inclusion of that component on the blog index page.

### CODE REVIEW

**Comment by paulpopus** [comment]
Left to do before merging is add:

* Author (name + optional link?)
* Date
* Metatags if they're not added

**Comment by willguv** [comment]
@paulpopus this looks great - thank you. A couple of things to fix if time?

1) Remove "Help us improve this page! (opens new window)" on the blog post list and all blog pages

2) On https://deploy-preview-23--trusting-noyce-aebebc.netlify.app/blog/a-brand-new-post.html is it easy to put the author credit line at the top? 

3) My name in the author credit links to Croydon.digital but presumably I can link to anywhere?

Other than that, top work!

You'll have to show me how to add images

**Comment by paulpopus** [comment]
@willguv 

1. Done!
2. Not really, the content inside the markdown is taken as one block, so I couldn't put the author and date under the title very easily.
3. Yes so when you edit the blog post in `/blog/a-brand-new-post.md` you have a author_url option if you wanted to link to your twitter for example.

The readme is updated with new instructions for blogging and adding images, it will update when this is merged in: https://github.com/localgovdrupal/docs/blob/1770980cea3fadd65b1e63c68bea68f19892ea30/README.md

**Comment by finnlewis** [comment]
This might be a personal preference, but I find dates in the url of blog posts to be really useful.

Is it possible to make the url include /2021-02/ or some such? 

If so, is it possible to make /2021-02/ list the posts from that month? 

If so, is it desirable?

**Comment by willguv** [comment]
> On second thoughts, I wonder if we should keep the edit links in there? I've seen it kept in other dev blogs and people open PRs to fix mistakes or add info.

Hi @paulpopus. I agree, but only on blog articles. There's not much point having it on the posting list

> This might be a personal preference, but I find dates in the url of blog posts to be really useful.

Hi @finnlewis, I've found this useful in the past but I wonder if we're unusual. Paul, how much effort do you think Finn's requests are?

**Comment by paulpopus** [comment]
@finnlewis @willguv 

> This might be a personal preference, but I find dates in the url of blog posts to be really useful.

I think it has become more unusual for the date to be in the URL. I don't think we can easily do that without some more extensive customisation to vuepress, in which case we will just end up with a too-complicated vue.js site as vuepress makes some assumptions about the content structure and routing.

We can always revisit this once we have more blog posts.

**Comment by willguv** [comment]
@paulpopus @finnlewis 

Thanks for the info - I think we should go with this as is. Ta for your help!

**Pull request merged**
