### PR TITLE
Remove blog files

### PR DESCRIPTION
**Pull request by keelanfh**
If the blog is no longer hosted on here, should we just remove the files?

### CODE REVIEW

**Comment by finnlewis** [comment]
Good call @keelanfh :)

**Comment by willguv** [comment]
Thanks @keelanfh and @finnlewis - there's definitely some blog posts missing so let's bring them over

@TJHDCR we can split this job if you like. Please let me know

**Comment by finnlewis** [comment]
Thanks @TimDCR ! Could you let us know when / if we should merge this?

**Comment by andybroomfield** [comment]
To check if blog entries have / need to be copied over to main blog site.

**Comment by finnlewis** [comment]
Hi @TimDCR @willguv 

Are we OK to lose the old blogs from the docs site now? 

If so, we can merge this one!

**Comment by willguv** [comment]
Yes think so - long superseded

**Comment by finnlewis** [comment]
Just chatting with @TimDCR 

@TimDCR do you want to double check if we want to copy any of these before deleting?

**Comment by TimDCR** [comment]
@finnlewis - I'm looking for the ticket I have on this - most can be deleted (out of date or duplicated from other sites) but it might be good to keep a couple - just for the record.

**Comment by finnlewis** [comment]
Thanks @TimDCR 

Do you want to let me know when we've copied what we need to the new blog location? 

Once done, we can merge this to tidy up the blogs site / repository.

Many thanks!

Finn

**Comment by millnut** [comment]
Hi @TimDCR are we ok to delete the blog content from the docs website now? I'd like to do this cleanup as part of https://github.com/localgovdrupal/docs/pull/273 if possible?

**Comment by TimDCR** [comment]
I moved over the important ones previously but failed to comment here.

They can now be removed from the docs site.

Cheers

**Comment by millnut** [comment]
Thanks @TimDCR ,  @finnlewis I've merged main with this PR and remove some additional code that was only used for blogs as part of the cleanup

**Review by msayoung — APPROVED** [review]

**Review by finnlewis — APPROVED** [review]
Awesome, thanks @TimDCR @millnut and @msayoung !!!

**Pull request merged**
